export const nationalLeagues = [
  {
    league: {
      id: 134,
      name: 'Torneo Federal A',
      type: 'League',
      logo: 'https://media-3.api-sports.io/football/leagues/134.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-3.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2023,
      start: '2023-03-12',
      end: '2023-10-29',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: true,
          statistics_fixtures: false,
          statistics_players: false,
        },
        standings: true,
        players: true,
        top_scorers: true,
        top_assists: true,
        top_cards: true,
        injuries: false,
        predictions: true,
        odds: true,
      },
    },
  },
  {
    league: {
      id: 129,
      name: 'Primera Nacional',
      type: 'League',
      logo: 'https://media-2.api-sports.io/football/leagues/129.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-2.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2023,
      start: '2023-02-04',
      end: '2023-10-21',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: true,
          statistics_fixtures: false,
          statistics_players: false,
        },
        standings: true,
        players: true,
        top_scorers: true,
        top_assists: true,
        top_cards: true,
        injuries: false,
        predictions: true,
        odds: true,
      },
    },
  },
  {
    league: {
      id: 131,
      name: 'Primera B Metropolitana',
      type: 'League',
      logo: 'https://media-2.api-sports.io/football/leagues/131.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-2.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2023,
      start: '2023-02-10',
      end: '2023-10-07',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: true,
          statistics_fixtures: false,
          statistics_players: false,
        },
        standings: true,
        players: true,
        top_scorers: true,
        top_assists: true,
        top_cards: true,
        injuries: false,
        predictions: true,
        odds: true,
      },
    },
  },
  {
    league: {
      id: 132,
      name: 'Primera C',
      type: 'League',
      logo: 'https://media-1.api-sports.io/football/leagues/132.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-3.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2023,
      start: '2023-01-27',
      end: '2023-10-07',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: false,
          statistics_fixtures: false,
          statistics_players: false,
        },
        standings: true,
        players: true,
        top_scorers: true,
        top_assists: true,
        top_cards: true,
        injuries: false,
        predictions: true,
        odds: true,
      },
    },
  },
  {
    league: {
      id: 133,
      name: 'Primera D',
      type: 'League',
      logo: 'https://media-3.api-sports.io/football/leagues/133.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-3.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2023,
      start: '2023-03-18',
      end: '2023-11-25',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: false,
          statistics_fixtures: false,
          statistics_players: false,
        },
        standings: true,
        players: true,
        top_scorers: true,
        top_assists: true,
        top_cards: true,
        injuries: false,
        predictions: true,
        odds: true,
      },
    },
  },
  {
    league: {
      id: 128,
      name: 'Liga Profesional Argentina',
      type: 'League',
      logo: 'https://media-2.api-sports.io/football/leagues/128.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-3.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2023,
      start: '2023-01-26',
      end: '2023-11-19',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: true,
          statistics_fixtures: true,
          statistics_players: true,
        },
        standings: true,
        players: true,
        top_scorers: true,
        top_assists: true,
        top_cards: true,
        injuries: false,
        predictions: true,
        odds: true,
      },
    },
  },
  {
    league: {
      id: 130,
      name: 'Copa Argentina',
      type: 'Cup',
      logo: 'https://media-3.api-sports.io/football/leagues/130.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-2.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2023,
      start: '2023-01-23',
      end: '2023-07-05',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: true,
          statistics_fixtures: false,
          statistics_players: false,
        },
        standings: false,
        players: false,
        top_scorers: false,
        top_assists: false,
        top_cards: false,
        injuries: false,
        predictions: true,
        odds: false,
      },
    },
  },
  {
    league: {
      id: 517,
      name: 'Trofeo de Campeones de la Superliga',
      type: 'Cup',
      logo: 'https://media-3.api-sports.io/football/leagues/517.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-1.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2023,
      start: '2023-02-23',
      end: '2023-03-01',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: true,
          statistics_fixtures: false,
          statistics_players: false,
        },
        standings: false,
        players: false,
        top_scorers: false,
        top_assists: false,
        top_cards: false,
        injuries: false,
        predictions: true,
        odds: false,
      },
    },
  },
  {
    league: {
      id: 810,
      name: 'Super Copa',
      type: 'Cup',
      logo: 'https://media-2.api-sports.io/football/leagues/810.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-3.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2023,
      start: '2023-03-01',
      end: '2023-03-01',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: true,
          statistics_fixtures: false,
          statistics_players: false,
        },
        standings: false,
        players: false,
        top_scorers: false,
        top_assists: false,
        top_cards: false,
        injuries: false,
        predictions: true,
        odds: false,
      },
    },
  },
  {
    league: {
      id: 483,
      name: 'Copa de la Superliga',
      type: 'Cup',
      logo: 'https://media-1.api-sports.io/football/leagues/483.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-2.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2020,
      start: '2020-03-13',
      end: '2020-12-23',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: true,
          statistics_fixtures: false,
          statistics_players: false,
        },
        standings: false,
        players: false,
        top_scorers: false,
        top_assists: false,
        top_cards: false,
        injuries: false,
        predictions: true,
        odds: false,
      },
    },
  },
  {
    league: {
      id: 906,
      name: 'Reserve League',
      type: 'League',
      logo: 'https://media-1.api-sports.io/football/leagues/906.png',
    },
    country: {
      name: 'Argentina',
      code: 'AR',
      flag: 'https://media-2.api-sports.io/flags/ar.svg',
    },
    seasons: {
      year: 2023,
      start: '2023-01-26',
      end: '2023-11-19',
      current: true,
      coverage: {
        fixtures: {
          events: true,
          lineups: false,
          statistics_fixtures: false,
          statistics_players: false,
        },
        standings: false,
        players: false,
        top_scorers: false,
        top_assists: false,
        top_cards: false,
        injuries: false,
        predictions: true,
        odds: true,
      },
    },
  },
]

export const leagueStatsData = {
  topScorers: [
    {
      player: {
        id: 75029,
        name: 'M. Guerreiro',
        firstname: 'Mariano',
        lastname: 'Guerreiro',
        age: 30,
        birth: {
          date: '1993-01-20',
          place: 'La Carlota',
          country: 'Argentina',
        },
        nationality: 'Argentina',
        height: '183 cm',
        weight: '83 kg',
        injured: false,
        photo: 'https://media-2.api-sports.io/football/players/75029.png',
      },
      statistics: [
        {
          team: {
            id: 18764,
            name: 'Argentino Monte Maíz',
            logo: 'https://media-2.api-sports.io/football/teams/18764.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-3.api-sports.io/football/leagues/134.png',
            flag: 'https://media-2.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 16,
            lineups: 16,
            minutes: 1268,
            number: null,
            position: 'Attacker',
            rating: null,
            captain: false,
          },
          substitutes: { in: 0, out: 14, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 8, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 2, yellowred: 0, red: 0 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 371574,
        name: 'M. Gutiérrez',
        firstname: 'Maximiliano Ezequiel',
        lastname: 'Gutiérrez',
        age: 26,
        birth: { date: '1997-01-04', place: 'Córdoba', country: 'Argentina' },
        nationality: 'Argentina',
        height: null,
        weight: null,
        injured: false,
        photo: 'https://media-1.api-sports.io/football/players/371574.png',
      },
      statistics: [
        {
          team: {
            id: 18764,
            name: 'Argentino Monte Maíz',
            logo: 'https://media-2.api-sports.io/football/teams/18764.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-1.api-sports.io/football/leagues/134.png',
            flag: 'https://media-3.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 16,
            lineups: 16,
            minutes: 1320,
            number: null,
            position: 'Midfielder',
            rating: null,
            captain: false,
          },
          substitutes: { in: 0, out: 13, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 8, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 2, yellowred: 0, red: 0 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 5830,
        name: 'M. Osurak',
        firstname: 'Maximiliano José',
        lastname: 'Osurak',
        age: 32,
        birth: { date: '1991-10-23', place: 'Santa Fe', country: 'Argentina' },
        nationality: 'Argentina',
        height: null,
        weight: null,
        injured: false,
        photo: 'https://media-3.api-sports.io/football/players/5830.png',
      },
      statistics: [
        {
          team: {
            id: 3982,
            name: 'Sol de América',
            logo: 'https://media-2.api-sports.io/football/teams/3982.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-3.api-sports.io/football/leagues/134.png',
            flag: 'https://media-1.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 13,
            lineups: 10,
            minutes: 940,
            number: null,
            position: 'Attacker',
            rating: null,
            captain: false,
          },
          substitutes: { in: 3, out: 6, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 8, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 1, yellowred: 0, red: 0 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 58480,
        name: 'F. Olego',
        firstname: 'Franco Leonel',
        lastname: 'Olego',
        age: 36,
        birth: { date: '1987-05-04', place: 'Ramallo', country: 'Argentina' },
        nationality: 'Argentina',
        height: '178 cm',
        weight: '75 kg',
        injured: false,
        photo: 'https://media-2.api-sports.io/football/players/58480.png',
      },
      statistics: [
        {
          team: {
            id: 1953,
            name: 'Sarmiento Resistencia',
            logo: 'https://media-2.api-sports.io/football/teams/1953.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-3.api-sports.io/football/leagues/134.png',
            flag: 'https://media-3.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 12,
            lineups: 12,
            minutes: 1080,
            number: null,
            position: 'Attacker',
            rating: null,
            captain: false,
          },
          substitutes: { in: 0, out: 1, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 8, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 1, yellowred: 0, red: 0 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
  ],
  topAssists: [],
  topYellowCards: [
    {
      player: {
        id: 75675,
        name: 'D. Núñez',
        firstname: 'Diego Jonathan',
        lastname: 'Núñez',
        age: 33,
        birth: { date: '1990-02-10', place: 'Arguello', country: 'Argentina' },
        nationality: 'Argentina',
        height: null,
        weight: null,
        injured: false,
        photo: 'https://media-3.api-sports.io/football/players/75675.png',
      },
      statistics: [
        {
          team: {
            id: 1966,
            name: 'Sportivo Belgrano',
            logo: 'https://media-2.api-sports.io/football/teams/1966.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-1.api-sports.io/football/leagues/134.png',
            flag: 'https://media-3.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 14,
            lineups: 13,
            minutes: 1078,
            number: null,
            position: 'Midfielder',
            rating: null,
            captain: false,
          },
          substitutes: { in: 1, out: 6, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 1, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 8, yellowred: 0, red: 0 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 411731,
        name: 'M. Alemandi',
        firstname: 'Martín',
        lastname: 'Alemandi',
        age: 24,
        birth: { date: '1999-09-30', place: null, country: 'Argentina' },
        nationality: 'Argentina',
        height: null,
        weight: null,
        injured: false,
        photo: 'https://media-1.api-sports.io/football/players/411731.png',
      },
      statistics: [
        {
          team: {
            id: 1950,
            name: 'Sportivo Las Parejas',
            logo: 'https://media-1.api-sports.io/football/teams/1950.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-1.api-sports.io/football/leagues/134.png',
            flag: 'https://media-2.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 15,
            lineups: 15,
            minutes: 1338,
            number: null,
            position: 'Defender',
            rating: null,
            captain: false,
          },
          substitutes: { in: 0, out: 1, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 0, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 7, yellowred: 0, red: 0 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 6140,
        name: 'A. Niz',
        firstname: 'Alexis Jorge',
        lastname: 'Niz',
        age: 35,
        birth: { date: '1988-05-17', place: 'Rafaela', country: 'Argentina' },
        nationality: 'Argentina',
        height: '179 cm',
        weight: '71 kg',
        injured: false,
        photo: 'https://media-3.api-sports.io/football/players/6140.png',
      },
      statistics: [
        {
          team: {
            id: 1934,
            name: 'Union Sunchales',
            logo: 'https://media-1.api-sports.io/football/teams/1934.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-1.api-sports.io/football/leagues/134.png',
            flag: 'https://media-1.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 15,
            lineups: 15,
            minutes: 1350,
            number: null,
            position: 'Defender',
            rating: null,
            captain: false,
          },
          substitutes: { in: 0, out: 0, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 0, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 7, yellowred: 0, red: 0 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 116430,
        name: 'J. Huichulef',
        firstname: 'Juan Cruz',
        lastname: 'Huichulef',
        age: 28,
        birth: { date: '1995-02-06', place: 'Ezeiza', country: 'Argentina' },
        nationality: 'Argentina',
        height: null,
        weight: null,
        injured: false,
        photo: 'https://media-1.api-sports.io/football/players/116430.png',
      },
      statistics: [
        {
          team: {
            id: 1941,
            name: 'Sol de Mayo',
            logo: 'https://media-2.api-sports.io/football/teams/1941.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-1.api-sports.io/football/leagues/134.png',
            flag: 'https://media-3.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 12,
            lineups: 9,
            minutes: 771,
            number: null,
            position: 'Defender',
            rating: null,
            captain: false,
          },
          substitutes: { in: 3, out: 0, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 1, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 6, yellowred: 1, red: 1 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
  ],
  topRedCards: [
    {
      player: {
        id: 361790,
        name: 'G. Ramírez',
        firstname: 'Gonzalo',
        lastname: 'Ramírez',
        age: 23,
        birth: { date: '2000-08-21', place: null, country: 'Argentina' },
        nationality: 'Argentina',
        height: null,
        weight: null,
        injured: false,
        photo: 'https://media-3.api-sports.io/football/players/361790.png',
      },
      statistics: [
        {
          team: {
            id: 3972,
            name: 'Germinal de Rawson',
            logo: 'https://media-1.api-sports.io/football/teams/3972.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-3.api-sports.io/football/leagues/134.png',
            flag: 'https://media-2.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 9,
            lineups: 9,
            minutes: 755,
            number: null,
            position: 'Defender',
            rating: null,
            captain: false,
          },
          substitutes: { in: 0, out: 0, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 0, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 5, yellowred: 0, red: 2 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 58542,
        name: 'L. Leguizamón',
        firstname: 'Luciano Félix',
        lastname: 'Leguizamón',
        age: 41,
        birth: {
          date: '1982-07-01',
          place: 'Concepción del Uruguay',
          country: 'Argentina',
        },
        nationality: 'Argentina',
        height: '175 cm',
        weight: '70 kg',
        injured: false,
        photo: 'https://media-1.api-sports.io/football/players/58542.png',
      },
      statistics: [
        {
          team: {
            id: 3945,
            name: 'Gimnasia Concepción',
            logo: 'https://media-1.api-sports.io/football/teams/3945.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-3.api-sports.io/football/leagues/134.png',
            flag: 'https://media-3.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 6,
            lineups: 4,
            minutes: 340,
            number: null,
            position: 'Attacker',
            rating: null,
            captain: false,
          },
          substitutes: { in: 2, out: 1, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 2, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 2, yellowred: 0, red: 2 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 57026,
        name: 'M. Del Col',
        firstname: 'Mariano Fernando',
        lastname: 'Del Col',
        age: 30,
        birth: {
          date: '1993-01-07',
          place: 'Buenos Aires',
          country: 'Argentina',
        },
        nationality: 'Argentina',
        height: '175 cm',
        weight: '67 kg',
        injured: false,
        photo: 'https://media-3.api-sports.io/football/players/57026.png',
      },
      statistics: [
        {
          team: {
            id: 467,
            name: 'Boca Unidos',
            logo: 'https://media-2.api-sports.io/football/teams/467.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-2.api-sports.io/football/leagues/134.png',
            flag: 'https://media-1.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 10,
            lineups: 8,
            minutes: 686,
            number: null,
            position: 'Defender',
            rating: null,
            captain: false,
          },
          substitutes: { in: 2, out: 2, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 0, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 1, yellowred: 0, red: 2 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
    {
      player: {
        id: 116430,
        name: 'J. Huichulef',
        firstname: 'Juan Cruz',
        lastname: 'Huichulef',
        age: 28,
        birth: { date: '1995-02-06', place: 'Ezeiza', country: 'Argentina' },
        nationality: 'Argentina',
        height: null,
        weight: null,
        injured: false,
        photo: 'https://media-1.api-sports.io/football/players/116430.png',
      },
      statistics: [
        {
          team: {
            id: 1941,
            name: 'Sol de Mayo',
            logo: 'https://media-1.api-sports.io/football/teams/1941.png',
          },
          league: {
            id: 134,
            name: 'Torneo Federal A',
            country: 'Argentina',
            logo: 'https://media-2.api-sports.io/football/leagues/134.png',
            flag: 'https://media-1.api-sports.io/flags/ar.svg',
            season: 2023,
          },
          games: {
            appearences: 12,
            lineups: 9,
            minutes: 771,
            number: null,
            position: 'Defender',
            rating: null,
            captain: false,
          },
          substitutes: { in: 3, out: 0, bench: 0 },
          shots: { total: null, on: null },
          goals: { total: 1, conceded: null, assists: null, saves: null },
          passes: { total: null, key: null, accuracy: null },
          tackles: { total: null, blocks: null, interceptions: null },
          duels: { total: null, won: null },
          dribbles: { attempts: null, success: null, past: null },
          fouls: { drawn: null, committed: null },
          cards: { yellow: 6, yellowred: 1, red: 1 },
          penalty: {
            won: null,
            commited: null,
            scored: null,
            missed: null,
            saved: null,
          },
        },
      ],
    },
  ],
}
