const pointTable = [
  {
    rank: 1,
    team: {
      id: 50,
      name: 'Manchester City',
      logo: 'https://media-1.api-sports.io/football/teams/50.png',
    },
    points: 89,
    goalsDiff: 61,
    group: 'Premier League',
    form: 'LDWWW',
    status: 'same',
    description: 'Promotion - Champions League (Group Stage: )',
    all: {
      played: 38,
      win: 28,
      draw: 5,
      lose: 5,
      goals: {
        for: 94,
        against: 33,
      },
    },
    home: {
      played: 19,
      win: 17,
      draw: 1,
      lose: 1,
      goals: {
        for: 60,
        against: 17,
      },
    },
    away: {
      played: 19,
      win: 11,
      draw: 4,
      lose: 4,
      goals: {
        for: 34,
        against: 16,
      },
    },
    update: '2023-05-28T00:00:00+00:00',
  },
]

// const pointTable = [
//   {
//     rank: 1,
//     team: {
//       id: 50,
//       name: 'Manchester City',
//       logo: 'https://media-1.api-sports.io/football/teams/50.png',
//     },
//     points: 89,
//     goalsDiff: 61,
//     group: 'Premier League',
//     form: 'LDWWW',
//     status: 'same',
//     description: 'Promotion - Champions League (Group Stage: )',
//     all: {
//       played: 38,
//       win: 28,
//       draw: 5,
//       lose: 5,
//       goals: {
//         for: 94,
//         against: 33,
//       },
//     },
//     home: {
//       played: 19,
//       win: 17,
//       draw: 1,
//       lose: 1,
//       goals: {
//         for: 60,
//         against: 17,
//       },
//     },
//     away: {
//       played: 19,
//       win: 11,
//       draw: 4,
//       lose: 4,
//       goals: {
//         for: 34,
//         against: 16,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 2,
//     team: {
//       id: 42,
//       name: 'Arsenal',
//       logo: 'https://media-3.api-sports.io/football/teams/42.png',
//     },
//     points: 84,
//     goalsDiff: 45,
//     group: 'Premier League',
//     form: 'WLLWW',
//     status: 'same',
//     description: 'Promotion - Champions League (Group Stage: )',
//     all: {
//       played: 38,
//       win: 26,
//       draw: 6,
//       lose: 6,
//       goals: {
//         for: 88,
//         against: 43,
//       },
//     },
//     home: {
//       played: 19,
//       win: 14,
//       draw: 3,
//       lose: 2,
//       goals: {
//         for: 53,
//         against: 25,
//       },
//     },
//     away: {
//       played: 19,
//       win: 12,
//       draw: 3,
//       lose: 4,
//       goals: {
//         for: 35,
//         against: 18,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 3,
//     team: {
//       id: 33,
//       name: 'Manchester United',
//       logo: 'https://media-2.api-sports.io/football/teams/33.png',
//     },
//     points: 75,
//     goalsDiff: 15,
//     group: 'Premier League',
//     form: 'WWWWL',
//     status: 'same',
//     description: 'Promotion - Champions League (Group Stage: )',
//     all: {
//       played: 38,
//       win: 23,
//       draw: 6,
//       lose: 9,
//       goals: {
//         for: 58,
//         against: 43,
//       },
//     },
//     home: {
//       played: 19,
//       win: 15,
//       draw: 3,
//       lose: 1,
//       goals: {
//         for: 36,
//         against: 10,
//       },
//     },
//     away: {
//       played: 19,
//       win: 8,
//       draw: 3,
//       lose: 8,
//       goals: {
//         for: 22,
//         against: 33,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 4,
//     team: {
//       id: 34,
//       name: 'Newcastle',
//       logo: 'https://media-2.api-sports.io/football/teams/34.png',
//     },
//     points: 71,
//     goalsDiff: 35,
//     group: 'Premier League',
//     form: 'DDWDL',
//     status: 'same',
//     description: 'Promotion - Champions League (Group Stage: )',
//     all: {
//       played: 38,
//       win: 19,
//       draw: 14,
//       lose: 5,
//       goals: {
//         for: 68,
//         against: 33,
//       },
//     },
//     home: {
//       played: 19,
//       win: 11,
//       draw: 6,
//       lose: 2,
//       goals: {
//         for: 36,
//         against: 14,
//       },
//     },
//     away: {
//       played: 19,
//       win: 8,
//       draw: 8,
//       lose: 3,
//       goals: {
//         for: 32,
//         against: 19,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 5,
//     team: {
//       id: 40,
//       name: 'Liverpool',
//       logo: 'https://media-3.api-sports.io/football/teams/40.png',
//     },
//     points: 67,
//     goalsDiff: 28,
//     group: 'Premier League',
//     form: 'DDWWW',
//     status: 'same',
//     description: 'Promotion - Europa League (Group Stage: )',
//     all: {
//       played: 38,
//       win: 19,
//       draw: 10,
//       lose: 9,
//       goals: {
//         for: 75,
//         against: 47,
//       },
//     },
//     home: {
//       played: 19,
//       win: 13,
//       draw: 5,
//       lose: 1,
//       goals: {
//         for: 46,
//         against: 17,
//       },
//     },
//     away: {
//       played: 19,
//       win: 6,
//       draw: 5,
//       lose: 8,
//       goals: {
//         for: 29,
//         against: 30,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 6,
//     team: {
//       id: 51,
//       name: 'Brighton',
//       logo: 'https://media-1.api-sports.io/football/teams/51.png',
//     },
//     points: 62,
//     goalsDiff: 19,
//     group: 'Premier League',
//     form: 'LDWLW',
//     status: 'same',
//     description: 'Promotion - Europa League (Group Stage: )',
//     all: {
//       played: 38,
//       win: 18,
//       draw: 8,
//       lose: 12,
//       goals: {
//         for: 72,
//         against: 53,
//       },
//     },
//     home: {
//       played: 19,
//       win: 10,
//       draw: 4,
//       lose: 5,
//       goals: {
//         for: 37,
//         against: 21,
//       },
//     },
//     away: {
//       played: 19,
//       win: 8,
//       draw: 4,
//       lose: 7,
//       goals: {
//         for: 35,
//         against: 32,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 7,
//     team: {
//       id: 66,
//       name: 'Aston Villa',
//       logo: 'https://media-1.api-sports.io/football/teams/66.png',
//     },
//     points: 61,
//     goalsDiff: 5,
//     group: 'Premier League',
//     form: 'WDWLL',
//     status: 'same',
//     description: 'Promotion - Europa Conference League (Qualification: )',
//     all: {
//       played: 38,
//       win: 18,
//       draw: 7,
//       lose: 13,
//       goals: {
//         for: 51,
//         against: 46,
//       },
//     },
//     home: {
//       played: 19,
//       win: 12,
//       draw: 2,
//       lose: 5,
//       goals: {
//         for: 33,
//         against: 21,
//       },
//     },
//     away: {
//       played: 19,
//       win: 6,
//       draw: 5,
//       lose: 8,
//       goals: {
//         for: 18,
//         against: 25,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 8,
//     team: {
//       id: 47,
//       name: 'Tottenham',
//       logo: 'https://media-2.api-sports.io/football/teams/47.png',
//     },
//     points: 60,
//     goalsDiff: 7,
//     group: 'Premier League',
//     form: 'WLLWL',
//     status: 'same',
//     description: null,
//     all: {
//       played: 38,
//       win: 18,
//       draw: 6,
//       lose: 14,
//       goals: {
//         for: 70,
//         against: 63,
//       },
//     },
//     home: {
//       played: 19,
//       win: 12,
//       draw: 1,
//       lose: 6,
//       goals: {
//         for: 37,
//         against: 25,
//       },
//     },
//     away: {
//       played: 19,
//       win: 6,
//       draw: 5,
//       lose: 8,
//       goals: {
//         for: 33,
//         against: 38,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 9,
//     team: {
//       id: 55,
//       name: 'Brentford',
//       logo: 'https://media-2.api-sports.io/football/teams/55.png',
//     },
//     points: 59,
//     goalsDiff: 12,
//     group: 'Premier League',
//     form: 'WWWLW',
//     status: 'same',
//     description: null,
//     all: {
//       played: 38,
//       win: 15,
//       draw: 14,
//       lose: 9,
//       goals: {
//         for: 58,
//         against: 46,
//       },
//     },
//     home: {
//       played: 19,
//       win: 10,
//       draw: 7,
//       lose: 2,
//       goals: {
//         for: 35,
//         against: 18,
//       },
//     },
//     away: {
//       played: 19,
//       win: 5,
//       draw: 7,
//       lose: 7,
//       goals: {
//         for: 23,
//         against: 28,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 10,
//     team: {
//       id: 36,
//       name: 'Fulham',
//       logo: 'https://media-3.api-sports.io/football/teams/36.png',
//     },
//     points: 52,
//     goalsDiff: 2,
//     group: 'Premier League',
//     form: 'LDWWL',
//     status: 'same',
//     description: null,
//     all: {
//       played: 38,
//       win: 15,
//       draw: 7,
//       lose: 16,
//       goals: {
//         for: 55,
//         against: 53,
//       },
//     },
//     home: {
//       played: 19,
//       win: 8,
//       draw: 5,
//       lose: 6,
//       goals: {
//         for: 31,
//         against: 29,
//       },
//     },
//     away: {
//       played: 19,
//       win: 7,
//       draw: 2,
//       lose: 10,
//       goals: {
//         for: 24,
//         against: 24,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 11,
//     team: {
//       id: 52,
//       name: 'Crystal Palace',
//       logo: 'https://media-1.api-sports.io/football/teams/52.png',
//     },
//     points: 45,
//     goalsDiff: -9,
//     group: 'Premier League',
//     form: 'DDWLW',
//     status: 'same',
//     description: null,
//     all: {
//       played: 38,
//       win: 11,
//       draw: 12,
//       lose: 15,
//       goals: {
//         for: 40,
//         against: 49,
//       },
//     },
//     home: {
//       played: 19,
//       win: 7,
//       draw: 7,
//       lose: 5,
//       goals: {
//         for: 21,
//         against: 23,
//       },
//     },
//     away: {
//       played: 19,
//       win: 4,
//       draw: 5,
//       lose: 10,
//       goals: {
//         for: 19,
//         against: 26,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 12,
//     team: {
//       id: 49,
//       name: 'Chelsea',
//       logo: 'https://media-2.api-sports.io/football/teams/49.png',
//     },
//     points: 44,
//     goalsDiff: -9,
//     group: 'Premier League',
//     form: 'DLLDW',
//     status: 'same',
//     description: null,
//     all: {
//       played: 38,
//       win: 11,
//       draw: 11,
//       lose: 16,
//       goals: {
//         for: 38,
//         against: 47,
//       },
//     },
//     home: {
//       played: 19,
//       win: 6,
//       draw: 7,
//       lose: 6,
//       goals: {
//         for: 20,
//         against: 19,
//       },
//     },
//     away: {
//       played: 19,
//       win: 5,
//       draw: 4,
//       lose: 10,
//       goals: {
//         for: 18,
//         against: 28,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 13,
//     team: {
//       id: 39,
//       name: 'Wolves',
//       logo: 'https://media-1.api-sports.io/football/teams/39.png',
//     },
//     points: 41,
//     goalsDiff: -27,
//     group: 'Premier League',
//     form: 'LDLWL',
//     status: 'same',
//     description: null,
//     all: {
//       played: 38,
//       win: 11,
//       draw: 8,
//       lose: 19,
//       goals: {
//         for: 31,
//         against: 58,
//       },
//     },
//     home: {
//       played: 19,
//       win: 9,
//       draw: 3,
//       lose: 7,
//       goals: {
//         for: 19,
//         against: 20,
//       },
//     },
//     away: {
//       played: 19,
//       win: 2,
//       draw: 5,
//       lose: 12,
//       goals: {
//         for: 12,
//         against: 38,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 14,
//     team: {
//       id: 48,
//       name: 'West Ham',
//       logo: 'https://media-1.api-sports.io/football/teams/48.png',
//     },
//     points: 40,
//     goalsDiff: -13,
//     group: 'Premier League',
//     form: 'LWLWL',
//     status: 'same',
//     description: null,
//     all: {
//       played: 38,
//       win: 11,
//       draw: 7,
//       lose: 20,
//       goals: {
//         for: 42,
//         against: 55,
//       },
//     },
//     home: {
//       played: 19,
//       win: 8,
//       draw: 4,
//       lose: 7,
//       goals: {
//         for: 26,
//         against: 24,
//       },
//     },
//     away: {
//       played: 19,
//       win: 3,
//       draw: 3,
//       lose: 13,
//       goals: {
//         for: 16,
//         against: 31,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 15,
//     team: {
//       id: 35,
//       name: 'Bournemouth',
//       logo: 'https://media-3.api-sports.io/football/teams/35.png',
//     },
//     points: 39,
//     goalsDiff: -34,
//     group: 'Premier League',
//     form: 'LLLLW',
//     status: 'same',
//     description: null,
//     all: {
//       played: 38,
//       win: 11,
//       draw: 6,
//       lose: 21,
//       goals: {
//         for: 37,
//         against: 71,
//       },
//     },
//     home: {
//       played: 19,
//       win: 6,
//       draw: 4,
//       lose: 9,
//       goals: {
//         for: 20,
//         against: 28,
//       },
//     },
//     away: {
//       played: 19,
//       win: 5,
//       draw: 2,
//       lose: 12,
//       goals: {
//         for: 17,
//         against: 43,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 16,
//     team: {
//       id: 65,
//       name: 'Nottingham Forest',
//       logo: 'https://media-1.api-sports.io/football/teams/65.png',
//     },
//     points: 38,
//     goalsDiff: -30,
//     group: 'Premier League',
//     form: 'DWDWL',
//     status: 'same',
//     description: null,
//     all: {
//       played: 38,
//       win: 9,
//       draw: 11,
//       lose: 18,
//       goals: {
//         for: 38,
//         against: 68,
//       },
//     },
//     home: {
//       played: 19,
//       win: 8,
//       draw: 6,
//       lose: 5,
//       goals: {
//         for: 27,
//         against: 24,
//       },
//     },
//     away: {
//       played: 19,
//       win: 1,
//       draw: 5,
//       lose: 13,
//       goals: {
//         for: 11,
//         against: 44,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 17,
//     team: {
//       id: 45,
//       name: 'Everton',
//       logo: 'https://media-3.api-sports.io/football/teams/45.png',
//     },
//     points: 36,
//     goalsDiff: -23,
//     group: 'Premier League',
//     form: 'WDLWD',
//     status: 'same',
//     description: null,
//     all: {
//       played: 38,
//       win: 8,
//       draw: 12,
//       lose: 18,
//       goals: {
//         for: 34,
//         against: 57,
//       },
//     },
//     home: {
//       played: 19,
//       win: 6,
//       draw: 3,
//       lose: 10,
//       goals: {
//         for: 16,
//         against: 27,
//       },
//     },
//     away: {
//       played: 19,
//       win: 2,
//       draw: 9,
//       lose: 8,
//       goals: {
//         for: 18,
//         against: 30,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 18,
//     team: {
//       id: 46,
//       name: 'Leicester',
//       logo: 'https://media-3.api-sports.io/football/teams/46.png',
//     },
//     points: 34,
//     goalsDiff: -17,
//     group: 'Premier League',
//     form: 'WDLLD',
//     status: 'same',
//     description: 'Relegation - Championship',
//     all: {
//       played: 38,
//       win: 9,
//       draw: 7,
//       lose: 22,
//       goals: {
//         for: 51,
//         against: 68,
//       },
//     },
//     home: {
//       played: 19,
//       win: 5,
//       draw: 4,
//       lose: 10,
//       goals: {
//         for: 23,
//         against: 27,
//       },
//     },
//     away: {
//       played: 19,
//       win: 4,
//       draw: 3,
//       lose: 12,
//       goals: {
//         for: 28,
//         against: 41,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 19,
//     team: {
//       id: 63,
//       name: 'Leeds',
//       logo: 'https://media-1.api-sports.io/football/teams/63.png',
//     },
//     points: 31,
//     goalsDiff: -30,
//     group: 'Premier League',
//     form: 'LLDLL',
//     status: 'same',
//     description: 'Relegation - Championship',
//     all: {
//       played: 38,
//       win: 7,
//       draw: 10,
//       lose: 21,
//       goals: {
//         for: 48,
//         against: 78,
//       },
//     },
//     home: {
//       played: 19,
//       win: 5,
//       draw: 7,
//       lose: 7,
//       goals: {
//         for: 26,
//         against: 37,
//       },
//     },
//     away: {
//       played: 19,
//       win: 2,
//       draw: 3,
//       lose: 14,
//       goals: {
//         for: 22,
//         against: 41,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
//   {
//     rank: 20,
//     team: {
//       id: 41,
//       name: 'Southampton',
//       logo: 'https://media-3.api-sports.io/football/teams/41.png',
//     },
//     points: 25,
//     goalsDiff: -37,
//     group: 'Premier League',
//     form: 'DLLLL',
//     status: 'same',
//     description: 'Relegation - Championship',
//     all: {
//       played: 38,
//       win: 6,
//       draw: 7,
//       lose: 25,
//       goals: {
//         for: 36,
//         against: 73,
//       },
//     },
//     home: {
//       played: 19,
//       win: 2,
//       draw: 5,
//       lose: 12,
//       goals: {
//         for: 19,
//         against: 37,
//       },
//     },
//     away: {
//       played: 19,
//       win: 4,
//       draw: 2,
//       lose: 13,
//       goals: {
//         for: 17,
//         against: 36,
//       },
//     },
//     update: '2023-05-28T00:00:00+00:00',
//   },
// ]

export const multiGroupTable = [
  [
    {
      rank: 1,
      team: {
        id: 789,
        name: 'Douglas Haig',
        logo: 'https://media-3.api-sports.io/football/teams/789.png',
      },
      points: 39,
      goalsDiff: 16,
      group: 'Torneo Federal A: Group 3',
      form: 'LWWWW',
      status: 'same',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 12,
        draw: 3,
        lose: 3,
        goals: {
          for: 25,
          against: 9,
        },
      },
      home: {
        played: 9,
        win: 8,
        draw: 0,
        lose: 1,
        goals: {
          for: 17,
          against: 5,
        },
      },
      away: {
        played: 9,
        win: 4,
        draw: 3,
        lose: 2,
        goals: {
          for: 8,
          against: 4,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 2,
      team: {
        id: 1960,
        name: 'Independiente De Chivilcoy',
        logo: 'https://media-1.api-sports.io/football/teams/1960.png',
      },
      points: 30,
      goalsDiff: 8,
      group: 'Torneo Federal A: Group 3',
      form: 'WLWWL',
      status: 'same',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 9,
        draw: 3,
        lose: 6,
        goals: {
          for: 20,
          against: 12,
        },
      },
      home: {
        played: 9,
        win: 6,
        draw: 2,
        lose: 1,
        goals: {
          for: 16,
          against: 3,
        },
      },
      away: {
        played: 9,
        win: 3,
        draw: 1,
        lose: 5,
        goals: {
          for: 4,
          against: 9,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 3,
      team: {
        id: 1950,
        name: 'Sportivo Las Parejas',
        logo: 'https://media-3.api-sports.io/football/teams/1950.png',
      },
      points: 29,
      goalsDiff: 7,
      group: 'Torneo Federal A: Group 3',
      form: 'WLWLW',
      status: 'up',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 9,
        draw: 2,
        lose: 7,
        goals: {
          for: 19,
          against: 12,
        },
      },
      home: {
        played: 9,
        win: 4,
        draw: 1,
        lose: 4,
        goals: {
          for: 9,
          against: 5,
        },
      },
      away: {
        played: 9,
        win: 5,
        draw: 1,
        lose: 3,
        goals: {
          for: 10,
          against: 7,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 4,
      team: {
        id: 1966,
        name: 'Sportivo Belgrano',
        logo: 'https://media-2.api-sports.io/football/teams/1966.png',
      },
      points: 28,
      goalsDiff: 6,
      group: 'Torneo Federal A: Group 3',
      form: 'DLDDL',
      status: 'down',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 8,
        draw: 4,
        lose: 6,
        goals: {
          for: 24,
          against: 18,
        },
      },
      home: {
        played: 9,
        win: 5,
        draw: 1,
        lose: 3,
        goals: {
          for: 12,
          against: 6,
        },
      },
      away: {
        played: 9,
        win: 3,
        draw: 3,
        lose: 3,
        goals: {
          for: 12,
          against: 12,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 5,
      team: {
        id: 1934,
        name: 'Union Sunchales',
        logo: 'https://media-2.api-sports.io/football/teams/1934.png',
      },
      points: 24,
      goalsDiff: -5,
      group: 'Torneo Federal A: Group 3',
      form: 'LLWWD',
      status: 'same',
      description: null,
      all: {
        played: 18,
        win: 7,
        draw: 3,
        lose: 8,
        goals: {
          for: 13,
          against: 18,
        },
      },
      home: {
        played: 9,
        win: 5,
        draw: 3,
        lose: 1,
        goals: {
          for: 9,
          against: 5,
        },
      },
      away: {
        played: 9,
        win: 2,
        draw: 0,
        lose: 7,
        goals: {
          for: 4,
          against: 13,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 6,
      team: {
        id: 21041,
        name: 'El Linqueño',
        logo: 'https://media-1.api-sports.io/football/teams/21041.png',
      },
      points: 23,
      goalsDiff: 1,
      group: 'Torneo Federal A: Group 3',
      form: 'DWLWL',
      status: 'same',
      description: null,
      all: {
        played: 18,
        win: 6,
        draw: 5,
        lose: 7,
        goals: {
          for: 22,
          against: 21,
        },
      },
      home: {
        played: 9,
        win: 3,
        draw: 2,
        lose: 4,
        goals: {
          for: 12,
          against: 11,
        },
      },
      away: {
        played: 9,
        win: 3,
        draw: 3,
        lose: 3,
        goals: {
          for: 10,
          against: 10,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 7,
      team: {
        id: 3942,
        name: 'Def. de Pronunciamiento',
        logo: 'https://media-3.api-sports.io/football/teams/3942.png',
      },
      points: 22,
      goalsDiff: -11,
      group: 'Torneo Federal A: Group 3',
      form: 'WWLLD',
      status: 'same',
      description: null,
      all: {
        played: 18,
        win: 6,
        draw: 4,
        lose: 8,
        goals: {
          for: 15,
          against: 26,
        },
      },
      home: {
        played: 9,
        win: 4,
        draw: 3,
        lose: 2,
        goals: {
          for: 12,
          against: 12,
        },
      },
      away: {
        played: 9,
        win: 2,
        draw: 1,
        lose: 6,
        goals: {
          for: 3,
          against: 14,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 8,
      team: {
        id: 2426,
        name: 'Defensores de Belgrano VR',
        logo: 'https://media-2.api-sports.io/football/teams/2426.png',
      },
      points: 15,
      goalsDiff: -9,
      group: 'Torneo Federal A: Group 3',
      form: 'LDLLW',
      status: 'same',
      description: null,
      all: {
        played: 17,
        win: 3,
        draw: 6,
        lose: 8,
        goals: {
          for: 12,
          against: 21,
        },
      },
      home: {
        played: 8,
        win: 2,
        draw: 2,
        lose: 4,
        goals: {
          for: 3,
          against: 7,
        },
      },
      away: {
        played: 9,
        win: 1,
        draw: 4,
        lose: 4,
        goals: {
          for: 9,
          against: 14,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 9,
      team: {
        id: 3945,
        name: 'Gimnasia Concepción',
        logo: 'https://media-3.api-sports.io/football/teams/3945.png',
      },
      points: 13,
      goalsDiff: -13,
      group: 'Torneo Federal A: Group 3',
      form: 'WLLDL',
      status: 'same',
      description: 'Relegation',
      all: {
        played: 17,
        win: 3,
        draw: 4,
        lose: 10,
        goals: {
          for: 13,
          against: 26,
        },
      },
      home: {
        played: 9,
        win: 3,
        draw: 3,
        lose: 3,
        goals: {
          for: 9,
          against: 10,
        },
      },
      away: {
        played: 8,
        win: 0,
        draw: 1,
        lose: 7,
        goals: {
          for: 4,
          against: 16,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
  ],
  [
    {
      rank: 1,
      team: {
        id: 443,
        name: 'Olimpo Bahia Blanca',
        logo: 'https://media-2.api-sports.io/football/teams/443.png',
      },
      points: 38,
      goalsDiff: 19,
      group: 'Torneo Federal A: Group 1',
      form: 'WWLDL',
      status: 'same',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 11,
        draw: 5,
        lose: 2,
        goals: {
          for: 30,
          against: 11,
        },
      },
      home: {
        played: 9,
        win: 7,
        draw: 2,
        lose: 0,
        goals: {
          for: 18,
          against: 4,
        },
      },
      away: {
        played: 9,
        win: 4,
        draw: 3,
        lose: 2,
        goals: {
          for: 12,
          against: 7,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 2,
      team: {
        id: 1938,
        name: 'Villa Mitre',
        logo: 'https://media-3.api-sports.io/football/teams/1938.png',
      },
      points: 33,
      goalsDiff: 15,
      group: 'Torneo Federal A: Group 1',
      form: 'WDDWD',
      status: 'same',
      description: 'Promotion Play-off',
      all: {
        played: 17,
        win: 9,
        draw: 6,
        lose: 2,
        goals: {
          for: 21,
          against: 6,
        },
      },
      home: {
        played: 9,
        win: 7,
        draw: 2,
        lose: 0,
        goals: {
          for: 16,
          against: 2,
        },
      },
      away: {
        played: 8,
        win: 2,
        draw: 4,
        lose: 2,
        goals: {
          for: 5,
          against: 4,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 3,
      team: {
        id: 475,
        name: 'Santamarina',
        logo: 'https://media-1.api-sports.io/football/teams/475.png',
      },
      points: 28,
      goalsDiff: 1,
      group: 'Torneo Federal A: Group 1',
      form: 'WDWDD',
      status: 'up',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 7,
        draw: 7,
        lose: 4,
        goals: {
          for: 16,
          against: 15,
        },
      },
      home: {
        played: 9,
        win: 3,
        draw: 6,
        lose: 0,
        goals: {
          for: 6,
          against: 3,
        },
      },
      away: {
        played: 9,
        win: 4,
        draw: 1,
        lose: 4,
        goals: {
          for: 10,
          against: 12,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 4,
      team: {
        id: 1930,
        name: 'Sansinena',
        logo: 'https://media-1.api-sports.io/football/teams/1930.png',
      },
      points: 26,
      goalsDiff: 3,
      group: 'Torneo Federal A: Group 1',
      form: 'DDDWW',
      status: 'down',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 7,
        draw: 5,
        lose: 6,
        goals: {
          for: 19,
          against: 16,
        },
      },
      home: {
        played: 9,
        win: 6,
        draw: 1,
        lose: 2,
        goals: {
          for: 14,
          against: 7,
        },
      },
      away: {
        played: 9,
        win: 1,
        draw: 4,
        lose: 4,
        goals: {
          for: 5,
          against: 9,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 5,
      team: {
        id: 1949,
        name: 'Cipolletti',
        logo: 'https://media-2.api-sports.io/football/teams/1949.png',
      },
      points: 24,
      goalsDiff: -1,
      group: 'Torneo Federal A: Group 1',
      form: 'DWWLW',
      status: 'same',
      description: null,
      all: {
        played: 18,
        win: 7,
        draw: 3,
        lose: 8,
        goals: {
          for: 20,
          against: 21,
        },
      },
      home: {
        played: 9,
        win: 6,
        draw: 0,
        lose: 3,
        goals: {
          for: 11,
          against: 6,
        },
      },
      away: {
        played: 9,
        win: 1,
        draw: 3,
        lose: 5,
        goals: {
          for: 9,
          against: 15,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 6,
      team: {
        id: 1941,
        name: 'Sol de Mayo',
        logo: 'https://media-1.api-sports.io/football/teams/1941.png',
      },
      points: 21,
      goalsDiff: -6,
      group: 'Torneo Federal A: Group 1',
      form: 'LWWDD',
      status: 'same',
      description: null,
      all: {
        played: 17,
        win: 6,
        draw: 3,
        lose: 8,
        goals: {
          for: 17,
          against: 23,
        },
      },
      home: {
        played: 8,
        win: 3,
        draw: 2,
        lose: 3,
        goals: {
          for: 13,
          against: 12,
        },
      },
      away: {
        played: 9,
        win: 3,
        draw: 1,
        lose: 5,
        goals: {
          for: 4,
          against: 11,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 7,
      team: {
        id: 18765,
        name: 'Liniers Bahía Blanca',
        logo: 'https://media-2.api-sports.io/football/teams/18765.png',
      },
      points: 18,
      goalsDiff: -8,
      group: 'Torneo Federal A: Group 1',
      form: 'LLLWL',
      status: 'same',
      description: null,
      all: {
        played: 18,
        win: 5,
        draw: 3,
        lose: 10,
        goals: {
          for: 13,
          against: 21,
        },
      },
      home: {
        played: 9,
        win: 4,
        draw: 2,
        lose: 3,
        goals: {
          for: 11,
          against: 8,
        },
      },
      away: {
        played: 9,
        win: 1,
        draw: 1,
        lose: 7,
        goals: {
          for: 2,
          against: 13,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 8,
      team: {
        id: 3972,
        name: 'Germinal de Rawson',
        logo: 'https://media-3.api-sports.io/football/teams/3972.png',
      },
      points: 17,
      goalsDiff: -10,
      group: 'Torneo Federal A: Group 1',
      form: 'DLLLL',
      status: 'same',
      description: null,
      all: {
        played: 18,
        win: 4,
        draw: 5,
        lose: 9,
        goals: {
          for: 16,
          against: 26,
        },
      },
      home: {
        played: 9,
        win: 2,
        draw: 3,
        lose: 4,
        goals: {
          for: 5,
          against: 9,
        },
      },
      away: {
        played: 9,
        win: 2,
        draw: 2,
        lose: 5,
        goals: {
          for: 11,
          against: 17,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 9,
      team: {
        id: 8399,
        name: 'Circulo Deportivo',
        logo: 'https://media-3.api-sports.io/football/teams/8399.png',
      },
      points: 15,
      goalsDiff: -13,
      group: 'Torneo Federal A: Group 1',
      form: 'DLLDL',
      status: 'same',
      description: 'Relegation',
      all: {
        played: 18,
        win: 4,
        draw: 3,
        lose: 11,
        goals: {
          for: 13,
          against: 26,
        },
      },
      home: {
        played: 9,
        win: 3,
        draw: 2,
        lose: 4,
        goals: {
          for: 9,
          against: 11,
        },
      },
      away: {
        played: 9,
        win: 1,
        draw: 1,
        lose: 7,
        goals: {
          for: 4,
          against: 15,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
  ],
  [
    {
      rank: 1,
      team: {
        id: 18764,
        name: 'Argentino Monte Maíz',
        logo: 'https://media-2.api-sports.io/football/teams/18764.png',
      },
      points: 38,
      goalsDiff: 22,
      group: 'Torneo Federal A: Group 2',
      form: 'DWWDW',
      status: 'same',
      description: 'Promotion Play-off',
      all: {
        played: 17,
        win: 11,
        draw: 5,
        lose: 1,
        goals: {
          for: 35,
          against: 13,
        },
      },
      home: {
        played: 8,
        win: 6,
        draw: 1,
        lose: 1,
        goals: {
          for: 21,
          against: 9,
        },
      },
      away: {
        played: 9,
        win: 5,
        draw: 4,
        lose: 0,
        goals: {
          for: 14,
          against: 4,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 2,
      team: {
        id: 16612,
        name: 'Ciudad de Bolívar',
        logo: 'https://media-3.api-sports.io/football/teams/16612.png',
      },
      points: 35,
      goalsDiff: 13,
      group: 'Torneo Federal A: Group 2',
      form: 'DLLWW',
      status: 'same',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 10,
        draw: 5,
        lose: 3,
        goals: {
          for: 26,
          against: 13,
        },
      },
      home: {
        played: 9,
        win: 7,
        draw: 2,
        lose: 0,
        goals: {
          for: 16,
          against: 4,
        },
      },
      away: {
        played: 9,
        win: 3,
        draw: 3,
        lose: 3,
        goals: {
          for: 10,
          against: 9,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 3,
      team: {
        id: 3947,
        name: 'Juventud Unida Univ.',
        logo: 'https://media-2.api-sports.io/football/teams/3947.png',
      },
      points: 26,
      goalsDiff: 1,
      group: 'Torneo Federal A: Group 2',
      form: 'WDDDL',
      status: 'up',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 6,
        draw: 8,
        lose: 4,
        goals: {
          for: 13,
          against: 12,
        },
      },
      home: {
        played: 9,
        win: 5,
        draw: 3,
        lose: 1,
        goals: {
          for: 9,
          against: 5,
        },
      },
      away: {
        played: 9,
        win: 1,
        draw: 5,
        lose: 3,
        goals: {
          for: 4,
          against: 7,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 4,
      team: {
        id: 2428,
        name: 'Huracan Las Heras',
        logo: 'https://media-1.api-sports.io/football/teams/2428.png',
      },
      points: 24,
      goalsDiff: -6,
      group: 'Torneo Federal A: Group 2',
      form: 'WDLLL',
      status: 'down',
      description: 'Promotion Play-off',
      all: {
        played: 17,
        win: 7,
        draw: 3,
        lose: 7,
        goals: {
          for: 16,
          against: 22,
        },
      },
      home: {
        played: 9,
        win: 6,
        draw: 1,
        lose: 2,
        goals: {
          for: 11,
          against: 8,
        },
      },
      away: {
        played: 8,
        win: 1,
        draw: 2,
        lose: 5,
        goals: {
          for: 5,
          against: 14,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 5,
      team: {
        id: 21043,
        name: 'Atenas',
        logo: 'https://media-2.api-sports.io/football/teams/21043.png',
      },
      points: 22,
      goalsDiff: -5,
      group: 'Torneo Federal A: Group 2',
      form: 'WDLLD',
      status: 'up',
      description: null,
      all: {
        played: 18,
        win: 6,
        draw: 4,
        lose: 8,
        goals: {
          for: 19,
          against: 24,
        },
      },
      home: {
        played: 9,
        win: 3,
        draw: 4,
        lose: 2,
        goals: {
          for: 10,
          against: 8,
        },
      },
      away: {
        played: 9,
        win: 3,
        draw: 0,
        lose: 6,
        goals: {
          for: 9,
          against: 16,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 6,
      team: {
        id: 3944,
        name: 'Ferro Carril Oeste LP',
        logo: 'https://media-1.api-sports.io/football/teams/3944.png',
      },
      points: 20,
      goalsDiff: -3,
      group: 'Torneo Federal A: Group 2',
      form: 'LWWLW',
      status: 'down',
      description: null,
      all: {
        played: 17,
        win: 6,
        draw: 2,
        lose: 9,
        goals: {
          for: 17,
          against: 20,
        },
      },
      home: {
        played: 9,
        win: 6,
        draw: 0,
        lose: 3,
        goals: {
          for: 13,
          against: 8,
        },
      },
      away: {
        played: 8,
        win: 0,
        draw: 2,
        lose: 6,
        goals: {
          for: 4,
          against: 12,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 7,
      team: {
        id: 21042,
        name: 'San Martín Mendoza',
        logo: 'https://media-2.api-sports.io/football/teams/21042.png',
      },
      points: 18,
      goalsDiff: -9,
      group: 'Torneo Federal A: Group 2',
      form: 'LLDWL',
      status: 'same',
      description: null,
      all: {
        played: 18,
        win: 4,
        draw: 6,
        lose: 8,
        goals: {
          for: 9,
          against: 18,
        },
      },
      home: {
        played: 9,
        win: 4,
        draw: 4,
        lose: 1,
        goals: {
          for: 5,
          against: 3,
        },
      },
      away: {
        played: 9,
        win: 0,
        draw: 2,
        lose: 7,
        goals: {
          for: 4,
          against: 15,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 8,
      team: {
        id: 477,
        name: 'Estudiantes S.l.',
        logo: 'https://media-2.api-sports.io/football/teams/477.png',
      },
      points: 17,
      goalsDiff: -5,
      group: 'Torneo Federal A: Group 2',
      form: 'DWLLW',
      status: 'same',
      description: null,
      all: {
        played: 18,
        win: 3,
        draw: 8,
        lose: 7,
        goals: {
          for: 17,
          against: 22,
        },
      },
      home: {
        played: 9,
        win: 3,
        draw: 4,
        lose: 2,
        goals: {
          for: 10,
          against: 8,
        },
      },
      away: {
        played: 9,
        win: 0,
        draw: 4,
        lose: 5,
        goals: {
          for: 7,
          against: 14,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 9,
      team: {
        id: 3960,
        name: 'Sportivo Peñarol',
        logo: 'https://media-2.api-sports.io/football/teams/3960.png',
      },
      points: 15,
      goalsDiff: -8,
      group: 'Torneo Federal A: Group 2',
      form: 'DLWWL',
      status: 'same',
      description: 'Relegation',
      all: {
        played: 17,
        win: 4,
        draw: 3,
        lose: 10,
        goals: {
          for: 15,
          against: 23,
        },
      },
      home: {
        played: 8,
        win: 3,
        draw: 3,
        lose: 2,
        goals: {
          for: 11,
          against: 8,
        },
      },
      away: {
        played: 9,
        win: 1,
        draw: 0,
        lose: 8,
        goals: {
          for: 4,
          against: 15,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
  ],
  [
    {
      rank: 1,
      team: {
        id: 1928,
        name: 'Gimnasia Y Tiro',
        logo: 'https://media-1.api-sports.io/football/teams/1928.png',
      },
      points: 34,
      goalsDiff: 11,
      group: 'Torneo Federal A: Group 4',
      form: 'WDWDD',
      status: 'same',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 9,
        draw: 7,
        lose: 2,
        goals: {
          for: 20,
          against: 9,
        },
      },
      home: {
        played: 9,
        win: 7,
        draw: 2,
        lose: 0,
        goals: {
          for: 16,
          against: 5,
        },
      },
      away: {
        played: 9,
        win: 2,
        draw: 5,
        lose: 2,
        goals: {
          for: 4,
          against: 4,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 2,
      team: {
        id: 1953,
        name: 'Sarmiento Resistencia',
        logo: 'https://media-2.api-sports.io/football/teams/1953.png',
      },
      points: 31,
      goalsDiff: 7,
      group: 'Torneo Federal A: Group 4',
      form: 'LWLDW',
      status: 'same',
      description: 'Promotion Play-off',
      all: {
        played: 19,
        win: 9,
        draw: 4,
        lose: 6,
        goals: {
          for: 19,
          against: 12,
        },
      },
      home: {
        played: 9,
        win: 5,
        draw: 2,
        lose: 2,
        goals: {
          for: 10,
          against: 4,
        },
      },
      away: {
        played: 10,
        win: 4,
        draw: 2,
        lose: 4,
        goals: {
          for: 9,
          against: 8,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 3,
      team: {
        id: 3982,
        name: 'Sol de América',
        logo: 'https://media-2.api-sports.io/football/teams/3982.png',
      },
      points: 26,
      goalsDiff: 4,
      group: 'Torneo Federal A: Group 4',
      form: 'LLWDW',
      status: 'same',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 7,
        draw: 5,
        lose: 6,
        goals: {
          for: 20,
          against: 16,
        },
      },
      home: {
        played: 9,
        win: 7,
        draw: 1,
        lose: 1,
        goals: {
          for: 15,
          against: 3,
        },
      },
      away: {
        played: 9,
        win: 0,
        draw: 4,
        lose: 5,
        goals: {
          for: 5,
          against: 13,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 4,
      team: {
        id: 1951,
        name: 'Central Norte',
        logo: 'https://media-2.api-sports.io/football/teams/1951.png',
      },
      points: 25,
      goalsDiff: 2,
      group: 'Torneo Federal A: Group 4',
      form: 'WWDWW',
      status: 'up',
      description: 'Promotion Play-off',
      all: {
        played: 18,
        win: 7,
        draw: 4,
        lose: 7,
        goals: {
          for: 21,
          against: 19,
        },
      },
      home: {
        played: 9,
        win: 5,
        draw: 2,
        lose: 2,
        goals: {
          for: 14,
          against: 7,
        },
      },
      away: {
        played: 9,
        win: 2,
        draw: 2,
        lose: 5,
        goals: {
          for: 7,
          against: 12,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 5,
      team: {
        id: 467,
        name: 'Boca Unidos',
        logo: 'https://media-1.api-sports.io/football/teams/467.png',
      },
      points: 24,
      goalsDiff: -6,
      group: 'Torneo Federal A: Group 4',
      form: 'DWDLD',
      status: 'same',
      description: null,
      all: {
        played: 18,
        win: 6,
        draw: 6,
        lose: 6,
        goals: {
          for: 15,
          against: 21,
        },
      },
      home: {
        played: 9,
        win: 6,
        draw: 2,
        lose: 1,
        goals: {
          for: 11,
          against: 5,
        },
      },
      away: {
        played: 9,
        win: 0,
        draw: 4,
        lose: 5,
        goals: {
          for: 4,
          against: 16,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 6,
      team: {
        id: 1961,
        name: 'Juventud Antoniana',
        logo: 'https://media-3.api-sports.io/football/teams/1961.png',
      },
      points: 23,
      goalsDiff: -5,
      group: 'Torneo Federal A: Group 4',
      form: 'LWDLD',
      status: 'down',
      description: null,
      all: {
        played: 18,
        win: 6,
        draw: 5,
        lose: 7,
        goals: {
          for: 12,
          against: 17,
        },
      },
      home: {
        played: 9,
        win: 4,
        draw: 5,
        lose: 0,
        goals: {
          for: 8,
          against: 4,
        },
      },
      away: {
        played: 9,
        win: 2,
        draw: 0,
        lose: 7,
        goals: {
          for: 4,
          against: 13,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 7,
      team: {
        id: 21040,
        name: '9 de Julio Rafaela',
        logo: 'https://media-1.api-sports.io/football/teams/21040.png',
      },
      points: 21,
      goalsDiff: -5,
      group: 'Torneo Federal A: Group 4',
      form: 'WLLWD',
      status: 'up',
      description: null,
      all: {
        played: 18,
        win: 6,
        draw: 3,
        lose: 9,
        goals: {
          for: 18,
          against: 23,
        },
      },
      home: {
        played: 9,
        win: 6,
        draw: 1,
        lose: 2,
        goals: {
          for: 13,
          against: 7,
        },
      },
      away: {
        played: 9,
        win: 0,
        draw: 2,
        lose: 7,
        goals: {
          for: 5,
          against: 16,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 8,
      team: {
        id: 1935,
        name: 'San Martin Formosa',
        logo: 'https://media-2.api-sports.io/football/teams/1935.png',
      },
      points: 20,
      goalsDiff: -2,
      group: 'Torneo Federal A: Group 4',
      form: 'DLLLL',
      status: 'down',
      description: null,
      all: {
        played: 18,
        win: 6,
        draw: 2,
        lose: 10,
        goals: {
          for: 12,
          against: 14,
        },
      },
      home: {
        played: 9,
        win: 6,
        draw: 2,
        lose: 1,
        goals: {
          for: 11,
          against: 2,
        },
      },
      away: {
        played: 9,
        win: 0,
        draw: 0,
        lose: 9,
        goals: {
          for: 1,
          against: 12,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
    {
      rank: 9,
      team: {
        id: 788,
        name: 'Crucero Del Norte',
        logo: 'https://media-2.api-sports.io/football/teams/788.png',
      },
      points: 19,
      goalsDiff: -6,
      group: 'Torneo Federal A: Group 4',
      form: 'DWLLL',
      status: 'down',
      description: 'Relegation',
      all: {
        played: 17,
        win: 5,
        draw: 4,
        lose: 8,
        goals: {
          for: 15,
          against: 21,
        },
      },
      home: {
        played: 9,
        win: 4,
        draw: 3,
        lose: 2,
        goals: {
          for: 10,
          against: 7,
        },
      },
      away: {
        played: 8,
        win: 1,
        draw: 1,
        lose: 6,
        goals: {
          for: 5,
          against: 14,
        },
      },
      update: '2023-07-14T00:00:00+00:00',
    },
  ],
]

export default pointTable
