const squadData = [
  {
    team: {
      id: 1,
      name: 'Belgium',
      logo: 'https://media-2.api-sports.io/football/teams/1.png',
    },
    players: [
      {
        id: 2096,
        name: 'A. Bodart',
        age: 25,
        number: null,
        position: 'Goalkeeper',
        photo: 'https://media-3.api-sports.io/football/players/2096.png',
      },
      {
        id: 730,
        name: 'T. Courtois',
        age: 31,
        number: null,
        position: 'Goalkeeper',
        photo: 'https://media-3.api-sports.io/football/players/730.png',
      },
      {
        id: 8471,
        name: 'T. Kaminski',
        age: 31,
        number: null,
        position: 'Goalkeeper',
        photo: 'https://media-3.api-sports.io/football/players/8471.png',
      },
      {
        id: 2919,
        name: 'M. Sels',
        age: 31,
        number: null,
        position: 'Goalkeeper',
        photo: 'https://media-2.api-sports.io/football/players/2919.png',
      },
      {
        id: 323449,
        name: 'A. Al-Dakhil',
        age: 21,
        number: null,
        position: 'Defender',
        photo: 'https://media-3.api-sports.io/football/players/323449.png',
      },
      {
        id: 1408,
        name: 'S. Bornauw',
        age: 24,
        number: null,
        position: 'Defender',
        photo: 'https://media-1.api-sports.io/football/players/1408.png',
      },
      {
        id: 2920,
        name: 'T. Castagne',
        age: 28,
        number: null,
        position: 'Defender',
        photo: 'https://media-2.api-sports.io/football/players/2920.png',
      },
      {
        id: 8694,
        name: 'W. Faes',
        age: 25,
        number: null,
        position: 'Defender',
        photo: 'https://media-2.api-sports.io/football/players/8694.png',
      },
      {
        id: 204043,
        name: 'A. Theate',
        age: 23,
        number: null,
        position: 'Defender',
        photo: 'https://media-1.api-sports.io/football/players/204043.png',
      },
      {
        id: 170,
        name: 'J. Vertonghen',
        age: 36,
        number: null,
        position: 'Defender',
        photo: 'https://media-1.api-sports.io/football/players/170.png',
      },
      {
        id: 629,
        name: 'K. De Bruyne',
        age: 32,
        number: null,
        position: 'Midfielder',
        photo: 'https://media-2.api-sports.io/football/players/629.png',
      },
      {
        id: 2922,
        name: 'L. Dendoncker',
        age: 28,
        number: null,
        position: 'Midfielder',
        photo: 'https://media-2.api-sports.io/football/players/2922.png',
      },
      {
        id: 2923,
        name: 'Y. Carrasco',
        age: 30,
        number: null,
        position: 'Midfielder',
        photo: 'https://media-2.api-sports.io/football/players/2923.png',
      },
      {
        id: 24882,
        name: 'O. Mangala',
        age: 25,
        number: null,
        position: 'Midfielder',
        photo: 'https://media-2.api-sports.io/football/players/24882.png',
      },
      {
        id: 1417,
        name: 'A. Saelemaekers',
        age: 24,
        number: null,
        position: 'Midfielder',
        photo: 'https://media-2.api-sports.io/football/players/1417.png',
      },
      {
        id: 2926,
        name: 'Y. Tielemans',
        age: 26,
        number: null,
        position: 'Midfielder',
        photo: 'https://media-1.api-sports.io/football/players/2926.png',
      },
      {
        id: 37381,
        name: 'M. Trésor',
        age: 24,
        number: null,
        position: 'Midfielder',
        photo: 'https://media-2.api-sports.io/football/players/37381.png',
      },
      {
        id: 78,
        name: 'H. Vanaken',
        age: 31,
        number: null,
        position: 'Midfielder',
        photo: 'https://media-3.api-sports.io/football/players/78.png',
      },
      {
        id: 127413,
        name: 'A. Vranckx',
        age: 21,
        number: null,
        position: 'Midfielder',
        photo: 'https://media-2.api-sports.io/football/players/127413.png',
      },
      {
        id: 290549,
        name: 'J. Bakayoko',
        age: 20,
        number: null,
        position: 'Attacker',
        photo: 'https://media-2.api-sports.io/football/players/290549.png',
      },
      {
        id: 2927,
        name: 'M. Batshuayi',
        age: 30,
        number: null,
        position: 'Attacker',
        photo: 'https://media-3.api-sports.io/football/players/2927.png',
      },
      {
        id: 8673,
        name: 'O. Deman',
        age: 23,
        number: null,
        position: 'Attacker',
        photo: 'https://media-1.api-sports.io/football/players/8673.png',
      },
      {
        id: 1422,
        name: 'J. Doku',
        age: 21,
        number: null,
        position: 'Attacker',
        photo: 'https://media-2.api-sports.io/football/players/1422.png',
      },
      {
        id: 907,
        name: 'R. Lukaku',
        age: 30,
        number: null,
        position: 'Attacker',
        photo: 'https://media-1.api-sports.io/football/players/907.png',
      },
      {
        id: 25458,
        name: 'D. Lukébakio',
        age: 26,
        number: null,
        position: 'Attacker',
        photo: 'https://media-1.api-sports.io/football/players/25458.png',
      },
      {
        id: 86,
        name: 'L. Openda',
        age: 23,
        number: null,
        position: 'Attacker',
        photo: 'https://media-3.api-sports.io/football/players/86.png',
      },
    ],
  },
]

export default squadData
